services:
  stats-server:
    container_name: stats-server
    ports:
      - "9090:9090"
    build: stats-server

  stats-db:
    image: postgres:16.1

  ewm-service:
    build: main-service
    image: explore-with-me-main-service
    container_name: explore-with-me-main-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:16.1
